# default structrue, just a set-up!
version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379"
    # address: redis://localhost
    # volumes:
    # - redis-db: /var/opt/redislabs
# volumes:
# redis-db:
# driver: local
